function [methodinfo,structs,enuminfo,ThunkLibName]=riceHeader
%RICEHEADER Create structures to define interfaces found in 'rice'.

%This function was generated by loadlibrary.m parser version 1.1.6.32 on Mon Jun 14 23:53:23 2010
%perl options:'rice.i -outfile=riceHeader.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
%  int Rice_Compress ( void *, void *, unsigned int , int ); 
fcns.name{fcnNum}='Rice_Compress'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'voidPtr', 'voidPtr', 'uint32', 'int32'};fcnNum=fcnNum+1;
%  void Rice_Uncompress ( void *, void *, unsigned int , unsigned int , int ); 
fcns.name{fcnNum}='Rice_Uncompress'; fcns.calltype{fcnNum}='cdecl'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'voidPtr', 'voidPtr', 'uint32', 'uint32', 'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;